name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore BMECat.net/BMECat.net.csproj 
           dotnet restore BMECat.net-Test/BMECat.net-Test.csproj
    - name: Build
      run: dotnet build BMECat.net/BMECat.net.csproj --no-restore
           dotnet build BMECat.net-Test/BMECat.net-Test.csproj --no-restore
    - name: Test
      run: dotnet test BMECat.net-Test/BMECat.net-Test.csproj --no-build --verbosity normal        
